# Lists of nonzero pixel coordinates
When working with adjacency matrices (also known as touch-matrices, proximal-neighbor-matrices and n-nearest-neighbor matrices) and also with images resulting from minima and maxima detection, a common task is to retrieve lists of coordinates from a given input image where the input image contained non-zero values. In numpy, the corresponding operation is called [nonzero](https://numpy.org/doc/stable/reference/generated/numpy.nonzero.html) and in clesperanto the function [spots_to_pointlist](https://clij.github.io/clij2-docs/reference_spotsToPointList) does the same. `spots_to_pointlist` assumes a binary image as input which only contains `1` and `0` though.

**Note**: A major difference between numpy and clesperanto becomes apparent in this case: clesperanto's dimension ordering/naming is different: While `np.nonzero` returns this list of coordinates:
```
[[y0,y1,y2],[x0,x1,x2]]
```
clesperanto will return this list:
```
[[x0,x1,x2],[y0,y1,y2]]
```
Use `cle.flip(pointlist, flip_x=False)` to convert a `pointlist` retrieved from clesperanto to one that equals the list in numpy.

In [1]:
import numpy as np
import pyclesperanto as cle

cle.get_device()

(OpenCL) NVIDIA GeForce RTX 2080 SUPER (OpenCL 3.0 CUDA)
	Type: GPU
	Compute Units: 48
	Global Memory Size: 8366 MB
	Maximum Object Size: 2091 MB

## 2D case

In [2]:
label_image = np.asarray([
    [1,0,0,1],
    [0,0,1,0],
    [0,1,0,0]
])
print(label_image)

[[1 0 0 1]
 [0 0 1 0]
 [0 1 0 0]]


In [3]:
label_image.nonzero()

(array([0, 0, 1, 2]), array([0, 3, 2, 1]))

In [4]:
cl_label_image = cle.push(label_image)
print(cl_label_image)

[[1 0 0 1]
 [0 0 1 0]
 [0 1 0 0]]


In [5]:
cle.spots_to_pointlist(cl_label_image)

AttributeError: module 'pyclesperanto' has no attribute 'spots_to_pointlist'

In [ ]:
cle.flip(cle.spots_to_pointlist(cl_label_image), flip_x=True)

## 3D case

In [ ]:
label_image = np.asarray([[
        [1,0,0,1],
        [0,0,1,0],
        [0,1,0,0]
    ],[
        [0,0,0,0],
        [0,1,0,0],
        [0,0,0,0]
]])
print(label_image)

In [ ]:
label_image.nonzero()

In [ ]:
cl_label_image = cle.push(label_image)
print(cl_label_image)

In [ ]:
cle.spots_to_pointlist(cl_label_image)

In [ ]:
cle.flip(cle.spots_to_pointlist(cl_label_image), flip_x=False)