In [1]:
import pyclesperanto as cle
import numpy as np

In [2]:
arr = np.asarray( 
    [
        [ 1, 2, 3, 4, 5, 6, 7, 8, 9,10],
        [11,12,13,14,15,16,17,18,19,20],
        [21,22,23,24,25,26,27,28,29,30],
        [31,32,33,34,35,36,37,38,39,70],
        [41,42,43,44,45,46,47,48,49,50]
    ]
).astype(np.float32)
arr

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25., 26., 27., 28., 29., 30.],
       [31., 32., 33., 34., 35., 36., 37., 38., 39., 70.],
       [41., 42., 43., 44., 45., 46., 47., 48., 49., 50.]], dtype=float32)

In [3]:
fft_arr = cle.__experimental__.fft(cle.push(arr), None)
fft_arr

array([[ 1.3050000e+03,  0.0000000e+00, -7.2948933e-01,  9.4575645e+01,
        -1.5729488e+01,  6.2941242e+01, -3.4270512e+01,  4.6695259e+01,
        -4.9270508e+01,  2.5756550e+01, -5.5000000e+01,  0.0000000e+00],
       [-2.7427051e+02,  3.6172903e+02, -3.0000002e+01, -2.3192670e-06,
        -2.4270510e+01, -1.7633558e+01, -9.2705059e+00, -2.8531693e+01,
         9.2705097e+00, -2.8531698e+01,  2.4270510e+01, -1.7633556e+01],
       [-2.4072949e+02,  5.2698219e+01,  2.4270510e+01, -1.7633558e+01,
         3.0000000e+01,  1.4565600e-06,  2.4270506e+01,  1.7633554e+01,
         9.2705135e+00,  2.8531700e+01, -9.2705097e+00,  2.8531696e+01],
       [-2.4072949e+02, -5.2698219e+01, -9.2705078e+00,  2.8531696e+01,
        -2.4270508e+01,  1.7633556e+01, -2.9999998e+01,  8.6715681e-07,
        -2.4270514e+01, -1.7633560e+01, -9.2705097e+00, -2.8531696e+01],
       [-2.7427051e+02, -3.6172903e+02, -9.2705069e+00, -2.8531698e+01,
         9.2705069e+00, -2.8531694e+01,  2.4270510e+01, -1.7633556e+01,
         3.0000002e+01,  5.4175598e-07,  2.4270510e+01,  1.7633556e+01]],
      dtype=float32, mtype=buffer)

In [4]:
new_arr = cle.create_like(arr)
cle.__experimental__.ifft(fft_arr, new_arr)
new_arr

array([[ 1.0000002,  1.9999998,  3.0000005,  3.9999993,  5.       ,
         6.       ,  7.       ,  8.       ,  8.999999 , 10.       ],
       [11.       , 12.       , 13.       , 14.       , 15.       ,
        16.       , 17.       , 18.       , 19.       , 20.       ],
       [20.999996 , 21.999996 , 22.999996 , 23.999996 , 24.999996 ,
        25.999996 , 26.999996 , 27.999996 , 28.999996 , 29.999996 ],
       [31.       , 32.000004 , 33.       , 34.       , 35.000004 ,
        36.       , 37.000004 , 38.       , 39.       , 70.       ],
       [41.       , 42.       , 43.       , 44.       , 45.       ,
        46.       , 47.       , 48.       , 49.       , 50.       ]],
      dtype=float32, mtype=buffer)

In [5]:
np.allclose(arr, cle.pull(new_arr), atol=1e-100)

True

In [6]:
np.array_equal(arr, cle.pull(new_arr))

False