In [1]:
import pyclesperanto as cle
import numpy as np

In [2]:
arr = np.array([[[1,1,1,1,1,1,1,1,1],
                [2,2,2,2,2,2,2,2,2],
                [3,3,3,3,3,3,3,3,3],
                [4,4,4,4,4,4,4,4,4],
                [5,5,5,5,5,5,5,5,5]],
               [[1,1,1,1,1,1,1,1,1],
                [2,2,2,2,2,2,2,2,2],
                [3,3,3,3,3,3,3,3,3],
                [4,4,4,4,4,4,4,4,4],
                [5,5,5,5,5,5,5,5,5]]])
arr

array([[[1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5, 5, 5, 5]],

       [[1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5, 5, 5, 5]]])

In [3]:
cle.select_device('TX')

(OpenCL) NVIDIA GeForce RTX 2080 SUPER (OpenCL 3.0 CUDA)
	Type: GPU
	Compute Units: 48
	Global Memory Size: 8358 MB
	Maximum Object Size: 2089 MB

In [4]:
arr_gpu = cle.push(arr)
arr_gpu.shape

(2, 5, 9)

In [5]:
cp_arr = cle.create((2,5,9), np.int64)
arr_gpu.copy(cp_arr)
cp_arr

array([[[1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5, 5, 5, 5]],

       [[1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5, 5, 5, 5]]], mtype=buffer)

In [6]:
cle.pull(arr_gpu)

array([[[1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5, 5, 5, 5]],

       [[1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5, 5, 5, 5]]])

In [7]:
arr_gpu[-1]

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5]], mtype=buffer)

In [8]:
arr_gpu[0]

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5]], mtype=buffer)

In [9]:
arr_gpu[0,2:4,2:6]

array([[3, 3, 3, 3],
       [4, 4, 4, 4]], mtype=buffer)

In [10]:
arr_gpu[0,:,2:6]

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5]], mtype=buffer)

In [11]:
arr_gpu[0,2:4,2:6] = 15
arr_gpu

array([[[ 1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2],
        [ 3,  3, 15, 15, 15, 15,  3,  3,  3],
        [ 4,  4, 15, 15, 15, 15,  4,  4,  4],
        [ 5,  5,  5,  5,  5,  5,  5,  5,  5]],

       [[ 1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2],
        [ 3,  3,  3,  3,  3,  3,  3,  3,  3],
        [ 4,  4,  4,  4,  4,  4,  4,  4,  4],
        [ 5,  5,  5,  5,  5,  5,  5,  5,  5]]], mtype=buffer)

In [12]:
arr_gpu[0,...,2:6] = 15
arr_gpu

array([[[ 1,  1, 15, 15, 15, 15,  1,  1,  1],
        [ 2,  2, 15, 15, 15, 15,  2,  2,  2],
        [ 3,  3, 15, 15, 15, 15,  3,  3,  3],
        [ 4,  4, 15, 15, 15, 15,  4,  4,  4],
        [ 5,  5, 15, 15, 15, 15,  5,  5,  5]],

       [[ 1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2],
        [ 3,  3,  3,  3,  3,  3,  3,  3,  3],
        [ 4,  4,  4,  4,  4,  4,  4,  4,  4],
        [ 5,  5,  5,  5,  5,  5,  5,  5,  5]]], mtype=buffer)

In [13]:
arr_gpu[1,2:4,2:6] = np.ones((2,4)) * 100
arr_gpu

array([[[  1,   1,  15,  15,  15,  15,   1,   1,   1],
        [  2,   2,  15,  15,  15,  15,   2,   2,   2],
        [  3,   3,  15,  15,  15,  15,   3,   3,   3],
        [  4,   4,  15,  15,  15,  15,   4,   4,   4],
        [  5,   5,  15,  15,  15,  15,   5,   5,   5]],

       [[  1,   1,   1,   1,   1,   1,   1,   1,   1],
        [  2,   2,   2,   2,   2,   2,   2,   2,   2],
        [  3,   3, 100, 100, 100, 100,   3,   3,   3],
        [  4,   4, 100, 100, 100, 100,   4,   4,   4],
        [  5,   5,   5,   5,   5,   5,   5,   5,   5]]], mtype=buffer)

In [14]:
arr_gpu[1,1:4,7:9] = cle.asarray(np.ones((3,2)) * -8)
arr_gpu

copy (2, 5, 9) [1, 1, 7] <- (3, 2) [1, 3, 2]


array([[[  1,   1,  15,  15,  15,  15,   1,   1,   1],
        [  2,   2,  15,  15,  15,  15,   2,   2,   2],
        [  3,   3,  15,  15,  15,  15,   3,   3,   3],
        [  4,   4,  15,  15,  15,  15,   4,   4,   4],
        [  5,   5,  15,  15,  15,  15,   5,   5,   5]],

       [[  1,   1,   1,   1,   1,   1,   1,   1,   1],
        [  2,   2,   2,   2,   2,   2,   2,  -8,  -8],
        [  3,   3, 100, 100, 100, 100,   3,  -8,  -8],
        [  4,   4, 100, 100, 100, 100,   4,  -8,  -8],
        [  5,   5,   5,   5,   5,   5,   5,   5,   5]]], mtype=buffer)