# Numpy interoperability example

This notebook shows example of interroperability between numpy and pyclesperanto. This does not remove any data transfert from host and device but demonstrate API compatiblity.

> Thie is WIP, some function will fail and it is normal, sorry for that

In [36]:
import numpy as np
import pyclesperanto as cle

cle.select_device()

(OpenCL) NVIDIA GeForce RTX 4090 (OpenCL 3.0 CUDA)
	Vendor:                      NVIDIA Corporation
	Driver Version:              535.216.01
	Device Type:                 GPU
	Compute Units:               128
	Global Memory Size:          24217 MB
	Maximum Object Size:         6054 MB
	Max Clock Frequency:         2625 MHz
	Image Support:               Yes

Most operation presented in this notebook only have a different function name, parameter name, or order. In order to facilitate interoperability between our library and the most used one by sci-py we redefined these operations to match as much as we could their API.

## Data conversion
To convert data back and forth between numpy and pyclesperanto, we can use both libraries' `asarray()` functions.

In [2]:
data = [[1, 2], [3, 4]]

In [3]:
np_data = np.asarray(data)
np_data

array([[1, 2],
       [3, 4]])

In [4]:
cle_data = cle.asarray(data)
cle_data

array([[1, 2],
       [3, 4]], dtype=int32, mtype=buffer)

In [5]:
np.asarray(cle_data)

array([[1, 2],
       [3, 4]], dtype=int32)

In [6]:
print(cle.asarray(np_data))

[[1 2]
 [3 4]]


## Replacing `nan` and `inf` values
... using `nan_to_num()`

In [7]:
cle_inf_data = cle.asarray([[-np.inf],
                            [np.inf],
                            [np.nan],
                           [0],
                           [1]])
print(cle_inf_data)

[[-inf]
 [ inf]
 [ nan]
 [  0.]
 [  1.]]


In [8]:
print(cle.nan_to_num(cle_inf_data, nan=3, posinf=4, neginf=5))

[[5.]
 [4.]
 [3.]
 [0.]
 [1.]]


Note, if you do not specify `posinf` and `neginf`, result may differ. They both fullfill the specification though as they set the values to "very large" and "very small".

In [9]:
np.nan_to_num([[np.inf]])

array([[1.79769313e+308]])

In [10]:
print(cle.nan_to_num([[np.inf]]))

[[3.4028235e+38]]


## Determining the presign of pixels

In [11]:
data = np.asarray([[-np.inf],
                    [np.inf],
                    [np.nan],
                    [0],
                    [1],
                    [-1]])

In [12]:
np.sign(data)

array([[-1.],
       [ 1.],
       [nan],
       [ 0.],
       [ 1.],
       [-1.]])

In [13]:
cle.sign(data)

array([[-1.],
       [ 1.],
       [nan],
       [ 0.],
       [ 1.],
       [-1.]], dtype=float32, mtype=buffer)

## Absolute

In [14]:
data = [[-3, 4]]

In [15]:
np.fabs(data)

array([[3., 4.]])

In [16]:
cle.fabs(data)

AttributeError: module 'pyclesperanto' has no attribute 'fabs'

In [17]:
cle.fabs.__name__

AttributeError: module 'pyclesperanto' has no attribute 'fabs'

## Square

In [18]:
np.square(data)

array([[ 9, 16]])

In [19]:
cle.square(data)

array([[ 9., 16.]], dtype=float32, mtype=buffer)

## Cubic root

In [20]:
data = [[27, 8]]

In [21]:
np.cbrt(data)

array([[3., 2.]])

In [22]:
cle.cbrt(data)

AttributeError: module 'pyclesperanto' has no attribute 'cbrt'

## Clip

In [23]:
data = [[1,2], [3,4]]

In [24]:
np.clip(data, a_min=2, a_max=3)

array([[2, 2],
       [3, 3]])

In [25]:
cle.clip(data, a_min=2, a_max=3)

TypeError: got an unexpected keyword argument 'a_min'

## Modulo

In [26]:
test = [[4, 5]]
test_div = [[2, 2]]

In [27]:
np.mod(test, test_div)

array([[0, 1]])

In [28]:
cle.mod(test, test_div)

AttributeError: module 'pyclesperanto' has no attribute 'mod'

## Compare arrays

In [29]:
data1 = np.asarray([[1, 2]])
data2 = np.asarray([[1, 2]])
data3 = np.asarray([[1, 2, 3]])

In [30]:
np.array_equal(data1, data2)

True

In [31]:
np.array_equiv(data1, data2)

True

In [32]:
cle.array_equal(data1, data2)

True

In [33]:
cle.array_equiv(data1, data2)

AttributeError: module 'pyclesperanto' has no attribute 'array_equiv'

In [34]:
np.array_equiv(data1, data3)

False

In [35]:
cle.array_equiv(data1, data3)

AttributeError: module 'pyclesperanto' has no attribute 'array_equiv'